### PR TITLE
Renaming Playfab to PlayFab in UE plugin for consistency and proper working.

### LINKED ISSUE #136: Inconsistent names in UE plugin
**To Reproduce**
1. Try to open project on MacOS with PlayFabGSDK plugin
2. Get an error

**Expected behavior**
Project open without any error with PlayFabGSDK.

**Desktop (please complete the following information):**
 - OS: MacOS

### PR DESCRIPTION
**Pull request by igor-sadchenko**
Fix #136

### CODE REVIEW

**Comment by nassosterz-ms** [comment]
I am wondering why this hasnt been an issue all this time. Are you reproducing it only on MacOS?

Have you run alredy GenerateVisualStudioProjectFiles? If so, does this fail - succeed?

**Comment by igor-sadchenko** [comment]
It's appears only on MacOS with UE 5.0
Here is a log sample
```
LogCsvProfiler: Display: Metadata set : platform="Mac"
LogCsvProfiler: Display: Metadata set : config="Development"
LogCsvProfiler: Display: Metadata set : buildversion="++UE5+Release-5.0-CL-20979098"
LogCsvProfiler: Display: Metadata set : engineversion="5.0.3-20979098+++UE5+Release-5.0"
LogCsvProfiler: Display: Metadata set : commandline="" /Users/ts/prj/Prj.uproject""
LogCsvProfiler: Display: Metadata set : os="12.6.1 21G217"
LogCsvProfiler: Display: Metadata set : cpu="GenuineIntel|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz"
LogCsvProfiler: Display: Metadata set : pgoenabled="0"
LogCsvProfiler: Display: Metadata set : loginid="bf494c5b484573aa645ef7b887f2c306"
LogCsvProfiler: Display: Metadata set : llm="0"
LogPlatformFile: Not using cached read wrapper
LogStats: Stats thread started at 1.015197
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +2:00, Platform Override: ''
LogInit: Session CrashGUID >====================================================
         Session CrashGUID >   UECC-Mac-E53CA5C89041375E8A94E88A77EE1AAB
         Session CrashGUID >====================================================
...
Message dialog closed, result: Ok, title: Message, text: Plugin 'PlayfabGSDK' failed to load because module 'PlayFabGSDK' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
LogCore: Engine exit requested (reason: EngineExit() was called)
```

**Comment by dylanh724** [comment]
> I am wondering why this hasnt been an issue all this time. Are you reproducing it only on MacOS?

Windows is generally not prone to path case sensitivity

**Comment by Leonardo-Rocha** [comment]
I just reproduced here while building for Linux as well, I'll try the fix

**Review by nassosterz-ms — APPROVED** [review]

**Comment by nassosterz-ms** [comment]
@igor-sadchenko  can you resolve the conflicts so that I merge this?

**Comment by nassosterz-ms** [comment]
Opened a separate PR with the merge conflicts being resolved.

**Comment by nassosterz-ms** [comment]
Closing as: https://github.com/PlayFab/gsdk/pull/137/files is merged

**Pull request closed without merging**
